
server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/supermar?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  mvc:
    servlet:
      load-on-startup: 1
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
  messages:
    basename: i18n.login
  mybatis:
    mapper-locations: classpath:mapper/*.xml